version: '3.3'
services:
 bingblue-group-company:
  image: registry.cn-shanghai.aliyuncs.com/bingblue/group-company:1
  ports:
    - 80:80
  networks:
    - bingblue
  deploy:
   replicas: 1
   update_config:
    parallelism: 1
    delay: 10s
   restart_policy:
    condition: on-failure
networks:
  bingblue:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 10.88.0.0/16
